package entity;
// Generated 26-Mar-2016 11:54:59 by Hibernate Tools 4.3.1



/**
 * BanAn generated by hbm2java
 */
public class BanAn  implements java.io.Serializable {


     private int id;
     private Integer songuoitoida;
     private String tinhtrang;

    public BanAn() {
    }

	
    public BanAn(int id) {
        this.id = id;
    }
    public BanAn(int id, Integer songuoitoida, String tinhtrang) {
       this.id = id;
       this.songuoitoida = songuoitoida;
       this.tinhtrang = tinhtrang;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getSonguoitoida() {
        return this.songuoitoida;
    }
    
    public void setSonguoitoida(Integer songuoitoida) {
        this.songuoitoida = songuoitoida;
    }
    public String getTinhtrang() {
        return this.tinhtrang;
    }
    
    public void setTinhtrang(String tinhtrang) {
        this.tinhtrang = tinhtrang;
    }




}


