package entity;
// Generated 26-Mar-2016 11:54:59 by Hibernate Tools 4.3.1



/**
 * Calamviec generated by hbm2java
 */
public class Calamviec  implements java.io.Serializable {


     private int id;
     private String calamviec;
     private Integer ngaylamviec;
     private String tinhtrang;
     private String nhanvienxinphepvang;
     private String nhanvienditre;
     private String chamcong;

    public Calamviec() {
    }

	
    public Calamviec(int id) {
        this.id = id;
    }
    public Calamviec(int id, String calamviec, Integer ngaylamviec, String tinhtrang, String nhanvienxinphepvang, String nhanvienditre, String chamcong) {
       this.id = id;
       this.calamviec = calamviec;
       this.ngaylamviec = ngaylamviec;
       this.tinhtrang = tinhtrang;
       this.nhanvienxinphepvang = nhanvienxinphepvang;
       this.nhanvienditre = nhanvienditre;
       this.chamcong = chamcong;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCalamviec() {
        return this.calamviec;
    }
    
    public void setCalamviec(String calamviec) {
        this.calamviec = calamviec;
    }
    public Integer getNgaylamviec() {
        return this.ngaylamviec;
    }
    
    public void setNgaylamviec(Integer ngaylamviec) {
        this.ngaylamviec = ngaylamviec;
    }
    public String getTinhtrang() {
        return this.tinhtrang;
    }
    
    public void setTinhtrang(String tinhtrang) {
        this.tinhtrang = tinhtrang;
    }
    public String getNhanvienxinphepvang() {
        return this.nhanvienxinphepvang;
    }
    
    public void setNhanvienxinphepvang(String nhanvienxinphepvang) {
        this.nhanvienxinphepvang = nhanvienxinphepvang;
    }
    public String getNhanvienditre() {
        return this.nhanvienditre;
    }
    
    public void setNhanvienditre(String nhanvienditre) {
        this.nhanvienditre = nhanvienditre;
    }
    public String getChamcong() {
        return this.chamcong;
    }
    
    public void setChamcong(String chamcong) {
        this.chamcong = chamcong;
    }




}


