package entity;
// Generated 26-Mar-2016 11:54:59 by Hibernate Tools 4.3.1



/**
 * MonAn generated by hbm2java
 */
public class MonAn  implements java.io.Serializable {


     private int id;
     private String tenmonan;
     private String nguyenlieu;
     private Float gia;
     private String tinhtrang;
     private String trangthainguyenlieu;

    public MonAn() {
    }

	
    public MonAn(int id) {
        this.id = id;
    }
    public MonAn(int id, String tenmonan, String nguyenlieu, Float gia, String tinhtrang, String trangthainguyenlieu) {
       this.id = id;
       this.tenmonan = tenmonan;
       this.nguyenlieu = nguyenlieu;
       this.gia = gia;
       this.tinhtrang = tinhtrang;
       this.trangthainguyenlieu = trangthainguyenlieu;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTenmonan() {
        return this.tenmonan;
    }
    
    public void setTenmonan(String tenmonan) {
        this.tenmonan = tenmonan;
    }
    public String getNguyenlieu() {
        return this.nguyenlieu;
    }
    
    public void setNguyenlieu(String nguyenlieu) {
        this.nguyenlieu = nguyenlieu;
    }
    public Float getGia() {
        return this.gia;
    }
    
    public void setGia(Float gia) {
        this.gia = gia;
    }
    public String getTinhtrang() {
        return this.tinhtrang;
    }
    
    public void setTinhtrang(String tinhtrang) {
        this.tinhtrang = tinhtrang;
    }
    public String getTrangthainguyenlieu() {
        return this.trangthainguyenlieu;
    }
    
    public void setTrangthainguyenlieu(String trangthainguyenlieu) {
        this.trangthainguyenlieu = trangthainguyenlieu;
    }




}


