package entity;
// Generated 26-Mar-2016 11:54:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien  implements java.io.Serializable {


     private int id;
     private String hoten;
     private String giotinh;
     private Date ngaysinh;
     private Integer dienthoai;
     private String diachi;
     private Integer cmnd;
     private Date thoigianbatdau;
     private String trinhdovitinh;
     private String calamviec;
     private String vitri;
     private String nghiviec;

    public Nhanvien() {
    }

	
    public Nhanvien(int id) {
        this.id = id;
    }
    public Nhanvien(int id, String hoten, String giotinh, Date ngaysinh, Integer dienthoai, String diachi, Integer cmnd, Date thoigianbatdau, String trinhdovitinh, String calamviec, String vitri, String nghiviec) {
       this.id = id;
       this.hoten = hoten;
       this.giotinh = giotinh;
       this.ngaysinh = ngaysinh;
       this.dienthoai = dienthoai;
       this.diachi = diachi;
       this.cmnd = cmnd;
       this.thoigianbatdau = thoigianbatdau;
       this.trinhdovitinh = trinhdovitinh;
       this.calamviec = calamviec;
       this.vitri = vitri;
       this.nghiviec = nghiviec;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public String getGiotinh() {
        return this.giotinh;
    }
    
    public void setGiotinh(String giotinh) {
        this.giotinh = giotinh;
    }
    public Date getNgaysinh() {
        return this.ngaysinh;
    }
    
    public void setNgaysinh(Date ngaysinh) {
        this.ngaysinh = ngaysinh;
    }
    public Integer getDienthoai() {
        return this.dienthoai;
    }
    
    public void setDienthoai(Integer dienthoai) {
        this.dienthoai = dienthoai;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public Integer getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(Integer cmnd) {
        this.cmnd = cmnd;
    }
    public Date getThoigianbatdau() {
        return this.thoigianbatdau;
    }
    
    public void setThoigianbatdau(Date thoigianbatdau) {
        this.thoigianbatdau = thoigianbatdau;
    }
    public String getTrinhdovitinh() {
        return this.trinhdovitinh;
    }
    
    public void setTrinhdovitinh(String trinhdovitinh) {
        this.trinhdovitinh = trinhdovitinh;
    }
    public String getCalamviec() {
        return this.calamviec;
    }
    
    public void setCalamviec(String calamviec) {
        this.calamviec = calamviec;
    }
    public String getVitri() {
        return this.vitri;
    }
    
    public void setVitri(String vitri) {
        this.vitri = vitri;
    }
    public String getNghiviec() {
        return this.nghiviec;
    }
    
    public void setNghiviec(String nghiviec) {
        this.nghiviec = nghiviec;
    }




}


