package entity;
// Generated 26-Mar-2016 11:54:59 by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private String email;
     private String pass;
     private int userRole;

    public User() {
    }

	
    public User(String username, int userRole) {
        this.username = username;
        this.userRole = userRole;
    }
    public User(String username, String email, String pass, int userRole) {
       this.username = username;
       this.email = email;
       this.pass = pass;
       this.userRole = userRole;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public int getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(int userRole) {
        this.userRole = userRole;
    }




}


