/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import dao.SanPhamDao;
import entity.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.HibernateUtil;

/**
 *
 * @author My PC
 */
public class JlFrameMonAn extends javax.swing.JInternalFrame {
    private SanPhamDao spd = new SanPhamDao();

    /**
     * Creates new form JlFrameMonAn
     */
    public JlFrameMonAn() {
        initComponents();
        LoadData();
    }
    public void LoadData()
    {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID");
        dtm.addColumn("Tên món ăn");
        dtm.addColumn("Tình trạng");
        dtm.addColumn("Nguyên liệu");
        dtm.addColumn("TT nguyên liệu");
        dtm.addColumn("Giá bán");
       // System.out.println(spd.finAll().size());
        for (MonAn mon_an : this.spd.finAll()) {
            dtm.addRow(new Object[]{mon_an.getId(), mon_an.getTenmonan(), mon_an.getTinhtrang(), mon_an.getNguyenlieu(), mon_an.getTrangthainguyenlieu(),mon_an.getGia()});
        }
        jTableMonAn.setModel(dtm);
        jTableMonAn.repaint();
        jTableMonAn.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMonAn = new javax.swing.JTable();
        jBtnXoa = new javax.swing.JButton();
        jBtnThemMoi = new javax.swing.JButton();
        jBtnCapNhat = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTxtTinhTrang = new javax.swing.JTextField();
        jTxtTenMonAn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtNguyenLieu = new javax.swing.JTextField();
        jTxtTTNguyenLieu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtGiaBan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jFrame1.setMinimumSize(new java.awt.Dimension(1300, 0));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1200, 520));
        getContentPane().setLayout(null);

        jTableMonAn.setAutoCreateRowSorter(true);
        jTableMonAn.setBackground(new java.awt.Color(204, 204, 204));
        jTableMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên món ăn", "Tình trạng", "Nguyên liệu", "TT nguyên liệu", "Giá bán"
            }
        ));
        jTableMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMonAnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMonAn);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 30, 840, 170);

        jBtnXoa.setBackground(new java.awt.Color(204, 204, 204));
        jBtnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/symbol-delete-icon.png"))); // NOI18N
        jBtnXoa.setText("Xóa");
        jBtnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jBtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnXoa);
        jBtnXoa.setBounds(190, 310, 170, 70);

        jBtnThemMoi.setBackground(new java.awt.Color(204, 204, 204));
        jBtnThemMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/math-add-icon.png"))); // NOI18N
        jBtnThemMoi.setText("Thêm mới");
        jBtnThemMoi.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jBtnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnThemMoiActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnThemMoi);
        jBtnThemMoi.setBounds(190, 220, 170, 70);

        jBtnCapNhat.setBackground(new java.awt.Color(204, 204, 204));
        jBtnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-edit-redo-icon.png"))); // NOI18N
        jBtnCapNhat.setText("Cập nhật");
        jBtnCapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jBtnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCapNhatActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCapNhat);
        jBtnCapNhat.setBounds(190, 400, 170, 70);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setText("tình trạng");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(400, 350, 73, 19);
        getContentPane().add(jTxtTinhTrang);
        jTxtTinhTrang.setBounds(510, 350, 170, 30);
        getContentPane().add(jTxtTenMonAn);
        jTxtTenMonAn.setBounds(510, 290, 170, 30);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setText("tên món ăn");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(400, 290, 90, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 240, 21, 19);
        getContentPane().add(jTxtId);
        jTxtId.setBounds(510, 230, 170, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Nguyên liệu");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(710, 240, 100, 19);

        jTxtNguyenLieu.setForeground(new java.awt.Color(51, 51, 255));
        getContentPane().add(jTxtNguyenLieu);
        jTxtNguyenLieu.setBounds(860, 230, 170, 30);

        jTxtTTNguyenLieu.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jTxtTTNguyenLieu);
        jTxtTTNguyenLieu.setBounds(860, 290, 170, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("TT nguyên liệu");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(710, 300, 108, 19);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Giá bán");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(710, 360, 56, 19);
        getContentPane().add(jTxtGiaBan);
        jTxtGiaBan.setBounds(860, 350, 170, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, -20, 1230, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnXoaActionPerformed
        // TODO add your handling code here:
        int cf = JOptionPane.showConfirmDialog(null, "ban co muon xoa", "xac nhan", JOptionPane.YES_NO_OPTION);
        if(cf==JOptionPane.YES_OPTION)
        {
            String mon_an = this.jTableMonAn.getValueAt(this.jTableMonAn.getSelectedRow(),0).toString();
            if(this.spd.delete(spd.find(mon_an)))
            {
                JOptionPane.showMessageDialog(null, "Xoa mon an thanh cong");
            }else{
                JOptionPane.showMessageDialog(null, "Xoa mon an that bai");
                
            }
            
        }
        LoadData();
    }//GEN-LAST:event_jBtnXoaActionPerformed

    private void jBtnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCapNhatActionPerformed
        // TODO add your handling code here:
        SanPhamDao spd = new SanPhamDao();
        MonAn mon_an = new MonAn();
        mon_an.setId(Integer.parseInt(this.jTxtId.getText()));
        mon_an.setTenmonan(this.jTxtTenMonAn.getText());
        mon_an.setNguyenlieu(this.jTxtNguyenLieu.getText());
        mon_an.setTinhtrang(this.jTxtTinhTrang.getText());
        mon_an.setTrangthainguyenlieu(this.jTxtTTNguyenLieu.getText());
        mon_an.setGia(Float.parseFloat(this.jTxtGiaBan.getText()));
        if(spd.saveorupdate(mon_an)){
            JOptionPane.showMessageDialog(null, "cap nhat thanh cong");
            
        }else{
            JOptionPane.showMessageDialog(null, "cap nhat that bai");
        }
        LoadData();
       
    }//GEN-LAST:event_jBtnCapNhatActionPerformed

    private void jBtnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnThemMoiActionPerformed
        // TODO add your handling code here:
       SanPhamDao spd = new SanPhamDao();
        MonAn mon_an = new MonAn();
        mon_an.setId(Integer.parseInt(this.jTxtId.getText()));
        mon_an.setTenmonan(this.jTxtTenMonAn.getText());
        mon_an.setNguyenlieu(this.jTxtNguyenLieu.getText());
        mon_an.setTinhtrang(this.jTxtTinhTrang.getText());
        mon_an.setTrangthainguyenlieu(this.jTxtTTNguyenLieu.getText());
        mon_an.setGia(Float.parseFloat(this.jTxtGiaBan.getText()));
        if(spd.saveorupdate(mon_an)){
            JOptionPane.showMessageDialog(null, "them mon an thanh cong");
            
        }else{
            JOptionPane.showMessageDialog(null, "them mon an that bai");
        }
        LoadData();
    }//GEN-LAST:event_jBtnThemMoiActionPerformed

    private void jTableMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMonAnMouseClicked
        // TODO add your handling code here:
        String chuoi = this.jTableMonAn.getValueAt(this.jTableMonAn.getSelectedRow(),0).toString();
        MonAn mon_an = this.spd.find(chuoi);
        this.jTxtId.setText(String.valueOf(mon_an.getId()));
        this.jTxtTenMonAn.setText(mon_an.getTenmonan());
        this.jTxtTinhTrang.setText(String.valueOf(mon_an.getTinhtrang()));
        this.jTxtNguyenLieu.setText(mon_an.getNguyenlieu());
        this.jTxtTTNguyenLieu.setText(String.valueOf(mon_an.getTrangthainguyenlieu()));
        this.jTxtGiaBan.setText(Double.toString(mon_an.getGia()));
 
        
    }//GEN-LAST:event_jTableMonAnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCapNhat;
    private javax.swing.JButton jBtnThemMoi;
    private javax.swing.JButton jBtnXoa;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMonAn;
    private javax.swing.JTextField jTxtGiaBan;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtNguyenLieu;
    private javax.swing.JTextField jTxtTTNguyenLieu;
    private javax.swing.JTextField jTxtTenMonAn;
    private javax.swing.JTextField jTxtTinhTrang;
    // End of variables declaration//GEN-END:variables
}
