/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.sun.corba.se.impl.naming.cosnaming.InterOperableNamingImpl;
import dao.NhanVienDao;
import dao.SanPhamDao;
import entity.Nhanvien;
import util.HibernateUtil;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author My PC
 */
public class JlFrameQuanLyNhanVien extends javax.swing.JInternalFrame {
    private NhanVienDao nvd = new NhanVienDao();

    /**
     * Creates new form JlFrameQuanLyNhanVien
     */
    public JlFrameQuanLyNhanVien() {
       initComponents();
        LoadDate();
    }
    public void LoadDate()
    {
        
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID");
        dtm.addColumn("Họ tên ++++++++ ");
        dtm.addColumn("Giới tính");
        dtm.addColumn("Ngày sinh     ");
        dtm.addColumn("Điện thoại");
        dtm.addColumn("Địa chỉ");
        dtm.addColumn("Cmnd");
       // dtm.addColumn("Thời gian bắt đầu");
        dtm.addColumn(" Trình độ vi tính");
        dtm.addColumn("Ca làm việc");
        dtm.addColumn("Nghỉ việc");
        dtm.addColumn("Vị trí");
        
       // System.out.println(nvd.finAll().size());
        for (Nhanvien nv : nvd.finAll()) {
            dtm.addRow(new Object[]{nv.getId(),nv.getHoten(), nv.getGiotinh(),nv.getNgaysinh(),nv.getDienthoai(),
            nv.getDiachi(),nv.getCmnd(), nv.getTrinhdovitinh(),nv.getCalamviec()
            ,nv.getNghiviec(),nv.getVitri()});
            System.out.println("nv.getId()");
        }
        jTableNhanVien.setModel(dtm);
        jTableNhanVien.repaint();
        jTableNhanVien.revalidate();  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNhanVien = new javax.swing.JTable();
        jTxtId = new javax.swing.JTextField();
        jTxtHoten = new javax.swing.JTextField();
        jTxtDienthoai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTxtCmnd = new javax.swing.JTextField();
        jTxtDiaChi = new javax.swing.JTextField();
        jBtnCapNhat = new javax.swing.JButton();
        jBtnXoa = new javax.swing.JButton();
        jBtnThemMoi = new javax.swing.JButton();
        jCbCalamviec = new javax.swing.JComboBox<String>();
        jCbGioitinh = new javax.swing.JComboBox<String>();
        jCbVotri = new javax.swing.JComboBox<String>();
        jCbtrinhdotinhoc = new javax.swing.JComboBox<String>();
        jCbNghiviec = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(1200, 520));
        setPreferredSize(new java.awt.Dimension(1200, 520));
        getContentPane().setLayout(null);

        jTableNhanVien.setAutoCreateRowSorter(true);
        jTableNhanVien.setBackground(new java.awt.Color(204, 204, 204));
        jTableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Họ tên", "Giới tính", "Ngày sinh", "Điện thoại", "Địa chỉ", "Cmnd", "Trình độ vi tính", "Ca làm việc", "nghỉ việc", "Vị trí"
            }
        ));
        jTableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNhanVien);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 1160, 170);
        getContentPane().add(jTxtId);
        jTxtId.setBounds(510, 220, 192, 30);
        getContentPane().add(jTxtHoten);
        jTxtHoten.setBounds(510, 260, 192, 30);
        getContentPane().add(jTxtDienthoai);
        jTxtDienthoai.setBounds(510, 380, 192, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(420, 220, 21, 19);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Trình độ vi tính");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(780, 310, 112, 19);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Thời gian bắt đầu");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(780, 270, 127, 19);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("Ngày sinh");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 340, 74, 19);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Cmnd");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(780, 230, 41, 19);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Địa chỉ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 420, 52, 19);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("Điện thoại");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 380, 77, 19);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setText("Giới tính");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 300, 63, 19);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setText("Họ tên");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 260, 48, 19);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("Nghỉ việc");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(780, 390, 70, 19);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setText("Vị trí");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(780, 440, 50, 19);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setText("Ca làm việc");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(780, 350, 85, 19);

        jTxtCmnd.setForeground(new java.awt.Color(51, 51, 255));
        getContentPane().add(jTxtCmnd);
        jTxtCmnd.setBounds(920, 220, 190, 30);
        getContentPane().add(jTxtDiaChi);
        jTxtDiaChi.setBounds(510, 420, 190, 30);

        jBtnCapNhat.setBackground(new java.awt.Color(204, 204, 204));
        jBtnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actions-edit-redo-icon.png"))); // NOI18N
        jBtnCapNhat.setText("Cập nhật");
        jBtnCapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jBtnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCapNhatActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCapNhat);
        jBtnCapNhat.setBounds(70, 400, 170, 70);

        jBtnXoa.setBackground(new java.awt.Color(204, 204, 204));
        jBtnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/symbol-delete-icon.png"))); // NOI18N
        jBtnXoa.setText("Xóa");
        jBtnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jBtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnXoa);
        jBtnXoa.setBounds(70, 310, 170, 70);

        jBtnThemMoi.setBackground(new java.awt.Color(204, 204, 204));
        jBtnThemMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/math-add-icon.png"))); // NOI18N
        jBtnThemMoi.setText("Thêm mới");
        jBtnThemMoi.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jBtnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnThemMoiActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnThemMoi);
        jBtnThemMoi.setBounds(70, 220, 170, 70);

        jCbCalamviec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sang", "Chieu", "Toi", " " }));
        getContentPane().add(jCbCalamviec);
        jCbCalamviec.setBounds(920, 340, 190, 30);

        jCbGioitinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nu" }));
        getContentPane().add(jCbGioitinh);
        jCbGioitinh.setBounds(510, 300, 190, 30);

        jCbVotri.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Phuc Vu", "Dau Bep", "Le Tan", "Quan Ly", "Khac" }));
        getContentPane().add(jCbVotri);
        jCbVotri.setBounds(920, 430, 190, 30);

        jCbtrinhdotinhoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Word", "Exel", "Khac" }));
        getContentPane().add(jCbtrinhdotinhoc);
        jCbtrinhdotinhoc.setBounds(920, 300, 190, 30);

        jCbNghiviec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1" }));
        getContentPane().add(jCbNghiviec);
        jCbNghiviec.setBounds(920, 380, 190, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/33709955-Healthy-eating-background-studio-photography-of-different-fruits-and-vegetables-on-wooden-table-Stock-Photo.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, -20, 1260, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCapNhatActionPerformed
        // TODO add your handling code here:
        NhanVienDao nvd = new NhanVienDao();
        Nhanvien nv = new Nhanvien();
        nv.setId(Integer.parseInt(this.jTxtId.getText()));
        nv.setHoten(jTxtHoten.getText());
        nv.setGiotinh(jCbGioitinh.getSelectedItem().toString());
        DateFormat df = new SimpleDateFormat("");
        nv.setDienthoai(Integer.parseInt(jTxtDienthoai.getText()));
        nv.setDiachi(jTxtDiaChi.getText());
        nv.setCmnd(Integer.parseInt(jTxtCmnd.getText()));

        nv.setTrinhdovitinh(jCbtrinhdotinhoc.getSelectedItem().toString());
        nv.setCalamviec(jCbCalamviec.getSelectedItem().toString());
        nv.setNghiviec(jCbNghiviec.getSelectedItem().toString());
        //nv.setCaPhepnghi(Integer.parseInt(jCbCanghi.getSelectedItem().toString()));
        nv.setVitri(jCbVotri.getSelectedItem().toString());
        if(nvd.saveorupdate(nv))
        {
            JOptionPane.showMessageDialog(null, "cap nhat thanh cong");
            
        }else{
            JOptionPane.showMessageDialog(null, "cap nhat that bai that bai");
        }
        LoadDate();
        
        
    }//GEN-LAST:event_jBtnCapNhatActionPerformed

    private void jBtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnXoaActionPerformed
        // TODO add your handling code here:
        int cf = JOptionPane.showConfirmDialog(null, "ban co muon xoa", "xac nhan", JOptionPane.YES_NO_OPTION);
        if(cf==JOptionPane.YES_OPTION)
        {
            String chuoi = jTableNhanVien.getValueAt(jTableNhanVien.getSelectedRow(), 0).toString();
            if(nvd.delete(nvd.find(chuoi)))
            {
                JOptionPane.showMessageDialog(null, "Xoa thanh cong");
            }else{
                JOptionPane.showMessageDialog(null, "xoa that bai");
            }
        }
        LoadDate();
    }//GEN-LAST:event_jBtnXoaActionPerformed

    private void jBtnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnThemMoiActionPerformed
        // TODO add your handling code here:
        NhanVienDao nvd = new NhanVienDao();
        Nhanvien nv = new Nhanvien();
        nv.setId(Integer.parseInt(this.jTxtId.getText()));
        nv.setHoten(jTxtHoten.getText());
        nv.setGiotinh(jCbGioitinh.getSelectedItem().toString());
        DateFormat df = new SimpleDateFormat("");
        
        nv.setDienthoai(Integer.parseInt(jTxtDienthoai.getText()));
        nv.setDiachi(jTxtDiaChi.getText());
        nv.setCmnd(Integer.parseInt(jTxtCmnd.getText()));
    
        nv.setTrinhdovitinh(jCbtrinhdotinhoc.getSelectedItem().toString());
        nv.setCalamviec(jCbCalamviec.getSelectedItem().toString());
        nv.setNghiviec(jCbNghiviec.getSelectedItem().toString());
       // nv.setCaPhepnghi(Integer.parseInt(jCbCanghi.getSelectedItem().toString()));
        nv.setVitri(jCbVotri.getSelectedItem().toString());
        if(nvd.saveorupdate(nv))
        {
            JOptionPane.showMessageDialog(null, "them Nhan vien thanh cong");
            
        }else{
            JOptionPane.showMessageDialog(null, "them Nhan vien that bai");
        }
        LoadDate();
        
        
        
        
        
        
    }//GEN-LAST:event_jBtnThemMoiActionPerformed

    private void jTableNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNhanVienMouseClicked
        // TODO add your handling code here:
        String chuoi = jTableNhanVien.getValueAt(jTableNhanVien.getSelectedRow(),0).toString();
        Nhanvien nv = nvd.find(chuoi);
        jTxtId.setText(String.valueOf(nv.getId()));
        jTxtHoten.setText(nv.getHoten());
        jTxtCmnd.setText(String.valueOf(nv.getCmnd()));
        jTxtDiaChi.setText(nv.getDiachi());
        jCbGioitinh.setSelectedItem(nv.getGiotinh());
        jCbNghiviec.setSelectedItem(String.valueOf(nv.getNghiviec()));
        jCbGioitinh.setSelectedItem(nv.getTrinhdovitinh());
        jCbVotri.setSelectedItem(nv.getVitri());
        jTxtDienthoai.setText(String.valueOf(nv.getDienthoai()));
        jCbCalamviec.setSelectedItem(nv.getCalamviec());
        
        
    }//GEN-LAST:event_jTableNhanVienMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCapNhat;
    private javax.swing.JButton jBtnThemMoi;
    private javax.swing.JButton jBtnXoa;
    private javax.swing.JComboBox<String> jCbCalamviec;
    private javax.swing.JComboBox<String> jCbGioitinh;
    private javax.swing.JComboBox<String> jCbNghiviec;
    private javax.swing.JComboBox<String> jCbVotri;
    private javax.swing.JComboBox<String> jCbtrinhdotinhoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNhanVien;
    private javax.swing.JTextField jTxtCmnd;
    private javax.swing.JTextField jTxtDiaChi;
    private javax.swing.JTextField jTxtDienthoai;
    private javax.swing.JTextField jTxtHoten;
    private javax.swing.JTextField jTxtId;
    // End of variables declaration//GEN-END:variables
}
